### ISSUE TITLE
Svelte: 디버깅 및 개발 환경 구축

### ISSUE THREAD

**Issue by digitalisx** [digitalisx/web-practice#15]
Link : https://svelte.dev/blog/the-easiest-way-to-get-started

**Comment by Coreight98** [comment]
조금 더 간편한 셋팅을 원하시면 [vite](https://vitejs-kr.github.io/guide/#command-line-interface)를 참고하셔도 좋을거 같습니다.

**Comment by digitalisx** [comment]
@Coreight98 좋습니다, 한번 사용해보도록 할게요 :)
