### ISSUE TITLE
Javascript: Vue tutorial practice

### ISSUE THREAD

**Issue by digitalisx** [digitalisx/web-practice#36]
- 2장까지 정독 후 예제 코드 PR하기
- 모각소 당일 설명 예정

**Comment by subin5** [comment]
- vue.js 책이 어려워서 동영상 강의로 대체

**Comment by subin5** [comment]
- Fix: git add하는 과정에서 발생한 Whitespace error 수정
- 혹시 나중에 문제 생기면 아래 사이트 참고
https://blog.jaeyoon.io/2018/01/git-crlf.html
