### ISSUE TITLE
Vue: 웹 사이트 틀 제작하기

### ISSUE THREAD

**Issue by subin5** [digitalisx/web-practice#59]
- 여태까지 배운 내용을 바탕으로 사이트 기본 구조 제작하기
- vue의 기본 프로젝트 구성 및 옵션 설정하기
- router를 우선적으로 구성
- 틀을 우선적으로 설계한 이후에 style 적용하기

**Comment by digitalisx** [comment]
@subin5 이번에는 포크한 Repo로 branch를 파지마시고, 본 Repo에 Branch를 팔 수 있으면 거기에 파서 같이 작업하도록해요~
개설 안되면 말씀 부탁드립니다.

**Comment by subin5** [comment]
이미 포크한 Repo에서 branch로 작업중인데 본 Repo로 옮겨서 작업할까요?

**Comment by digitalisx** [comment]
네 관련된 옮기는 작업 관련해서 PR 올려주셔도 됩니다. + 리뷰 어싸인

**Comment by digitalisx** [comment]
@subin5 작업 범위는 사진을 이용한 각 단과대학 소개까지! 게시판은 제가 하겠습니다 :)
